plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-cayman

title: Gallant HubSpot Theme Documentation
description: Description
show_downloads: false
